/* ✅ Version 3.0.0 Newest update: Analyzer v3 Controller/Renderer. One parsed object powers UI, autofill, timers, and issue report. */
(function(){
  const VER='3.0.0';
  const clean=v=>String(v||'').replace(/\s+/g,' ').trim();
  const esc=v=>{if(window.esc)return window.esc(String(v??''));const d=document.createElement('div');d.textContent=String(v??'');return d.innerHTML};
  const money=n=>'$'+Number(n||0).toLocaleString();
  const pretty=d=>{try{return window.fD?window.fD(d):new Date(d+'T00:00:00').toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'})}catch{return d||''}};
  const isTerms=v=>String(v||'').length>160&&/(bonus|offer|eligible|qualifying|direct deposit|checking|monthly fee|terms|conditions|promo|bonus chart)/i.test(v||'');
  function analyze(raw,opts){return window.tcV3Analyze?window.tcV3Analyze(raw,opts):null}
  function currentResult(raw){return analyze(raw)||window.__tcV3AnalysisResult||null}
  function summaryHtml(r){if(!r)return'';const lines=[];lines.push('<div class="tc-label">SIMPLE TERMS:</div>');lines.push(r.tiered?`* Bonus: <span class="hl-money">Tiered ${esc(r.bonusTierText)}</span>`:`* Bonus: ${r.bonus?`<span class="hl-money">${money(r.bonus)}</span>`:'Review'}`);lines.push(`* Account: ${esc(r.acct||'Review')}`);if(r.code)lines.push(`* Promo code: <span class="hl-code">${esc(r.code)}</span>`);lines.push(`* Monthly fee: ${r.fee?`<span class="hl-fee">${money(r.fee)}</span>`:'Not clearly stated in pasted T&C'}`);if(r.waivers?.length)lines.push(`* Fee waiver: ${esc(r.waivers.slice(0,3).join(' OR '))}`);lines.push(`* Early close / payout risk: ${esc(r.early||'Keep account open and in good standing until payout.')}`);lines.push('');lines.push('<span class="hl-section">HOW TO EARN THE BONUS:</span>');let step=1;lines.push(`* ${step++}. Open one eligible account${r.openBy?` by <span class="hl-days">${pretty(r.openBy)}</span>`:''}${r.code?` using promo code <span class="hl-code">${esc(r.code)}</span>`:''}.`);if(r.fundedDays)lines.push(`* ${step++}. Fund the account${r.fundingAmount?` with at least <span class="hl-money">${money(r.fundingAmount)}</span>`:''} within <span class="hl-days">${r.fundedDays} days</span>.`);lines.push(`* ${step++}. Complete ${r.count?`at least <span class="hl-days">${r.count}</span> `:''}qualifying Direct Deposits${r.reqMoney?`${r.reqIsTotal?' totaling ':' of '}<span class="hl-money">${money(r.reqMoney)}+</span>${r.reqIsTotal?'':' each'}`:''}${r.reqDays?` within <span class="hl-days">${r.reqDays} days</span>`:''}.`);lines.push(`* ${step++}. Bonus payout: ${esc(r.payout||'payout timing needs review')}.`);lines.push(`* ${step++}. Keep account open and in good standing until payout.`);lines.push('');lines.push('<span class="hl-section">WHAT COUNTS:</span>');(r.counts?.length?r.counts:['Review qualifying deposit wording manually']).forEach(x=>lines.push(`* ${esc(x)}`));lines.push('');lines.push('<span class="hl-section">WHAT DOES NOT COUNT:</span>');(r.not?.length?r.not:['Not clearly listed']).forEach(x=>lines.push(`* <span class="hl-warn">${esc(x)}</span>`));if(r.waivers?.length){lines.push('');lines.push('<span class="hl-section">MONTHLY FEE CAN BE AVOIDED WITH:</span>');r.waivers.forEach(x=>lines.push(`* ${esc(x)}`));}lines.push('');lines.push('<span class="hl-section">ELIGIBILITY / CHURN:</span>');(r.eligibilityText?r.eligibilityText.split('\n'):['Review eligibility manually']).filter(Boolean).forEach(x=>lines.push(`* ${esc(x)}`));lines.push('');lines.push('<span class="hl-section">REVIEW:</span>');lines.push(r.clear?'* Qualification path is clear from pasted T&C. Verify target tier/account type before applying.':'* Qualification path needs manual review.');lines.push('');lines.push(`<span style="font-size:10px;color:#94a3b8">Source: ${esc(r.sourceKind||'unknown')} · Engine v3</span>`);return `<div class="tc-body">${lines.join('\n')}</div>`}
  function findSummaryCard(){return Array.from(document.querySelectorAll('.tc-box,.az-area,.card')).filter(el=>!el.querySelector('textarea,input,select')).filter(el=>{const t=el.textContent||'';return t.includes('SIMPLE TERMS')&&(t.includes('HOW TO EARN')||t.includes('WHAT COUNTS'))}).sort((a,b)=>(a.textContent||'').length-(b.textContent||'').length)[0]||null}
  function findRaw(){const tca=document.getElementById('tca_raw')?.value||'';if(isTerms(tca))return tca;const areas=Array.from(document.querySelectorAll('textarea')).map(a=>a.value||'').filter(isTerms).sort((a,b)=>b.length-a.length);return areas[0]||''}
  function renderSummary(){const raw=findRaw();if(!raw)return false;const r=currentResult(raw);const card=findSummaryCard();if(!card||!r)return false;card.dataset.v3='true';card.dataset.sourceKind=r.sourceKind||'';card.style.height='auto';card.style.maxHeight='none';card.style.overflow='visible';card.innerHTML=summaryHtml(r);return true}
  function modalObj(){try{return window.modal||null}catch{return null}}
  function applyToModal(r){const m=modalObj();if(!m||!r)return false;m.bank=m.bank||r.bank;if(r.bonus)m.bonus=r.bonus;if(r.reqDays)m.reqDays=r.reqDays;if(r.code)m.promoCodeText=r.code;if(r.openBy)m.expirationDateText=pretty(r.openBy);if(r.fee)m.monthlyFeeYNText=`Yes — ${money(r.fee)} monthly fee`;if(r.waivers?.length)m.avoidMonthlyFeeText=r.waivers.join('\n');if(r.actionPlan)m.completeBonusText=r.actionPlan;if(r.eligibilityText)m.eligibilityText=r.eligibilityText;if(r.early)m.earlyTerminationFeeText=r.early;if(r.fundedDays)m.fundedDays=r.fundedDays;if(r.fundingAmount)m.fundingAmount=r.fundingAmount;m.tcAnalysisResult=r;m.tcSourceRaw=r.raw;m.tcSourceId=r.sourceId;try{window.tcV3SaveSourceForCurrentEntry&&window.tcV3SaveSourceForCurrentEntry(r.raw,{bank:r.bank})}catch{}return true}
  function addDaysIso(start,days){try{if(window.addD)return window.addD(start,days)}catch{}const d=new Date(start+'T00:00:00');d.setDate(d.getDate()+Number(days||0));return d.toISOString().split('T')[0]}
  function createTimers(r){const m=modalObj();if(!m||!r)return 0;const opened=m.opened||'';m.customTimers=Array.isArray(m.customTimers)?m.customTimers:[];let added=0;const mk=(text,date,startDate='',daysRequired=0)=>({id:window.timerId?window.timerId():'tm_'+Math.random().toString(36).slice(2,8),text,date,startDate,daysRequired:Number(daysRequired||0),done:false});const add=t=>{if(!t.date)return;if(m.customTimers.some(x=>clean(x.text).toLowerCase()===clean(t.text).toLowerCase()&&x.date===t.date))return;m.customTimers.push(t);added++};if(r.openBy)add(mk('Promo expiration / open-by deadline',r.openBy));if(opened&&r.reqDays)add(mk('Bonus requirement deadline',addDaysIso(opened,r.reqDays),opened,r.reqDays));if(opened&&r.fundedDays)add(mk('Funding deadline',addDaysIso(opened,r.fundedDays),opened,r.fundedDays));return added}
  function issueReport(r){r=r||window.__tcV3AnalysisResult||currentResult(findRaw());if(!r)return'No analyzer result found.';return ['BANK BONUS TRACKER — v3 ANALYZER ISSUE REPORT','App Version: '+(document.querySelector('.app-version')?.textContent||'unknown'),'Engine: '+(window.tcV3EngineVersion||'unknown'),'Source: '+(r.sourceKind||'unknown'),'Bank: '+(r.bank||'Review'),'Bonus: '+(r.bonus||'Review'),'Tiers: '+(r.bonusTierText||'None'),'Promo Code: '+(r.code||'Review'),'Open-by: '+(r.openBy||'Review'),'Req Days: '+(r.reqDays||'Review'),'Req Amount: '+(r.reqMoney||'Review'),'Funding Days: '+(r.fundedDays||'—'),'Monthly Fee: '+(r.fee||'Review/None'),'Flags: '+(r.reviewFlags?.join(' | ')||'None'),'','SOURCE T&C:',String(r.raw||'').slice(0,15000)].join('\n')}
  function copyIssueReport(){const txt=issueReport();navigator.clipboard?.writeText(txt).then(()=>alert('Analyzer issue report copied.')).catch(()=>alert(txt))}
  function openPro(){const src=window.tcV3ResolveSource?window.tcV3ResolveSource(findRaw()):{raw:findRaw()};let r=analyze(src.raw);document.getElementById('tca_overlay')?.remove();let h=`<div class="cbg" onclick="tcClosePro()"><div class="dd-box tca-box" onclick="event.stopPropagation()"><h3>✨ Unified Analyzer Pro <span style="font-size:9px;color:#94A3B8">v3.0</span></h3><div class="sub">Clean v3 pipeline: current pasted text first, entry saved source second, vault fallback last.</div><textarea id="tca_raw" class="dd-input" style="height:150px;line-height:1.45">${esc(src.raw||'')}</textarea><div class="crow"><button class="c-c" onclick="tcClosePro()">Close</button><button class="c-g" onclick="tcRunPro()">Analyze</button></div><div id="tcv3_result">${summaryHtml(r)}</div>`;if(r?.tiers?.length){h+=`<div class="tc-box"><div class="tc-label">Target tier</div><select class="dd-input" onchange="tcV3SelectTier(this.value)">`;r.tiers.forEach((t,i)=>h+=`<option value="${i}" ${i===r.tiers.length-1?'selected':''}>${money(t.bonus)} bonus — ${money(t.requirement)}+ DD</option>`);h+=`</select></div>`}h+=`<div class="crow"><button class="c-c" onclick="tcCopyIssueReport()">🧾 Copy Issue Report</button><button class="c-g" onclick="tcApplyPro()">Apply Fields</button></div><button class="btn-p" style="margin-top:8px" onclick="tcCreateTimers()">Create Suggested Mini Timers</button></div></div>`;const d=document.createElement('div');d.id='tca_overlay';d.innerHTML=h;document.body.appendChild(d)}
  window.tcOpenPro=openPro;window.tcClosePro=()=>document.getElementById('tca_overlay')?.remove();window.tcRunPro=function(){const raw=document.getElementById('tca_raw')?.value||findRaw();const r=analyze(raw);const box=document.getElementById('tcv3_result');if(box)box.innerHTML=summaryHtml(r);renderSummary()};window.tcV3SelectTier=function(i){const raw=document.getElementById('tca_raw')?.value||findRaw();const r=analyze(raw,{tierIndex:Number(i)});const box=document.getElementById('tcv3_result');if(box)box.innerHTML=summaryHtml(r)};window.tcApplyPro=function(){const raw=document.getElementById('tca_raw')?.value||findRaw();const r=currentResult(raw);applyToModal(r);alert('Applied v3 analyzer fields. Review, then save entry.');try{window.R&&window.R()}catch{};window.tcClosePro()};window.tcCreateTimers=function(){const raw=document.getElementById('tca_raw')?.value||findRaw();const r=currentResult(raw);const n=createTimers(r);alert(n?`Created ${n} mini timer(s). Save the entry.`:'No timers created. Add Opened Date for start+days timers.');try{window.R&&window.R()}catch{}};window.tcCopyIssueReport=copyIssueReport;window.tcV3RenderSummary=renderSummary;window.tcV3ApplyToModal=applyToModal;window.tcV3CreateTimers=createTimers;
  document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const txt=clean(b.textContent||'');if(/analyz|hide analyzer|show analyzer|auto.?fill/i.test(txt))setTimeout(renderSummary,250);if(/Auto-fill New Entry/i.test(txt)){setTimeout(()=>{const r=currentResult(findRaw());applyToModal(r)},100)}} ,true);
  document.addEventListener('input',e=>{if(e.target?.tagName==='TEXTAREA')setTimeout(renderSummary,350)},true);
  setInterval(()=>{if(findSummaryCard())renderSummary()},2500);
  setTimeout(renderSummary,800);setTimeout(renderSummary,1800);
  const st=document.createElement('style');st.textContent=`.app-version::after{content:' · v3';opacity:.78}.tc-strict-card,[data-v3="true"]{height:auto!important;max-height:none!important;overflow:visible!important}`;document.head.appendChild(st);
})();
