/* ✅ Version 3.0.0 Newest update: Analyzer v3 Engine. One parser result powers summary, autofill, timers, and issue reports. */
(function(){
  const VER='3.0.0';
  const clean=v=>String(v||'').replace(/\s+/g,' ').trim();
  const escRe=s=>String(s||'').replace(/[.*+?^${}()|[\]\\]/g,'\\$&');
  const moneyNum=s=>{const n=parseFloat(String(s||'').replace(/[$,\s]/g,''));return Number.isFinite(n)?n:0};
  const money=n=>'$'+Number(n||0).toLocaleString();
  const uniq=a=>Array.from(new Set((a||[]).filter(Boolean).map(clean))).filter(Boolean);
  const mo={jan:1,january:1,feb:2,february:2,mar:3,march:3,apr:4,april:4,may:5,jun:6,june:6,jul:7,july:7,aug:8,august:8,sep:9,sept:9,september:9,oct:10,october:10,nov:11,november:11,dec:12,december:12};
  const pretty=iso=>{try{return window.fD?window.fD(iso):new Date(iso+'T00:00:00').toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'})}catch{return iso||''}};
  const split=t=>String(t||'').replace(/\r/g,'\n').split(/(?<=[.!?])\s+|\n+/).map(clean).filter(x=>x.length>6);
  function dates(s){const out=[];let m;const add=(y,mm,d,src='')=>{if(y&&mm&&d)out.push({iso:`${y}-${String(mm).padStart(2,'0')}-${String(d).padStart(2,'0')}`,source:src})};const r1=/\b(Jan(?:uary)?|Feb(?:ruary)?|Mar(?:ch)?|Apr(?:il)?|May|Jun(?:e)?|Jul(?:y)?|Aug(?:ust)?|Sep(?:t(?:ember)?)?|Oct(?:ober)?|Nov(?:ember)?|Dec(?:ember)?)\s+(\d{1,2})(?:st|nd|rd|th)?[,]?\s+(20\d{2})\b/gi;while((m=r1.exec(s)))add(m[3],mo[m[1].toLowerCase()],m[2],m[0]);const r2=/\b(\d{1,2})[\/\-](\d{1,2})[\/\-](20\d{2})\b/g;while((m=r2.exec(s)))add(m[3],m[1],m[2],m[0]);const r3=/\b(20\d{2})[-\/](\d{1,2})[-\/](\d{1,2})\b/g;while((m=r3.exec(s)))add(m[1],m[2],m[3],m[0]);return out;}
  function days(s){const out=[];String(s||'').replace(/(\d{1,4}|ninety|sixty|thirty|twelve)\s*(?:\((\d{1,4})\))?\s*(?:calendar\s*)?(day|days|month|months)/gi,(m,w,n,unit)=>{let v=parseInt(n||w,10);if(!v){const map={ninety:90,sixty:60,thirty:30,twelve:12};v=map[String(w).toLowerCase()]||0}if(/month/i.test(unit))v*=30;if(v>0)out.push({days:v,text:m});return m});return out;}
  function monies(s){const a=[];String(s||'').replace(/\$\s*([0-9]{1,3}(?:,[0-9]{3})*(?:\.\d+)?|[0-9]+(?:\.\d+)?)/g,m=>{a.push({value:moneyNum(m),text:m.replace(/\s+/g,'')});return m});return a;}
  function isDisclosure(s){return /\bas of\b|APY|Annual Percentage Yield|effective as of|rates?|StockBrokers|U\.S\. News|FDIC|ratesheet|depositsrates|trademark|overdraft|Erica|mobile banking requires/i.test(s||'')}
  function lineMatch(lines,res){return lines.find(l=>res.some(r=>r.test(l)))||''}
  function allMatch(lines,res){return lines.filter(l=>res.some(r=>r.test(l)))}
  function bank(raw){if(/Bank of America|BofA/i.test(raw))return'Bank of America';if(/U\.S\. Bank|US Bank|Bank Smartly/i.test(raw))return'U.S. Bank';if(/Morgan Stanley Private Bank|E\*TRADE/i.test(raw))return'Morgan Stanley Private Bank';if(/Wells Fargo/i.test(raw))return'Wells Fargo';if(/Chase/i.test(raw))return'Chase';if(/Capital One/i.test(raw))return'Capital One';if(/Citi(?:bank)?/i.test(raw))return'Citibank';if(/PNC/i.test(raw))return'PNC Bank';const m=raw.match(/([A-Z][A-Za-z&.'’\- ]{2,90}?(?:Bank|Credit Union|Private Bank))/);return m?clean(m[1]):'New Bank Bonus'}
  function account(raw){if(/Bank of America/i.test(raw))return'Bank of America eligible personal checking';if(/Bank Smartly/i.test(raw))return'U.S. Bank Smartly Checking';if(/Checking or Max-Rate Checking|Checking OR Max-Rate Checking/i.test(raw))return'Checking OR Max-Rate Checking — open one only; do not enroll both';if(/consumer checking/i.test(raw))return'consumer checking';if(/personal checking/i.test(raw))return'personal checking';if(/business checking/i.test(raw))return'business checking';if(/checking/i.test(raw))return'checking';return'account type needs review'}
  function normalize(raw){let out=String(raw||'');try{if(window.tcNormalizeWeirdBankWording)out=window.tcNormalizeWeirdBankWording(out)}catch{}return out}
  function tiers(raw){const text=String(raw||'').replace(/\s+/g,' ');const out=[];const push=(req,max,bonus,src)=>{req=moneyNum(req);max=moneyNum(max);bonus=moneyNum(bonus);if(req>=100&&bonus>0&&bonus<req)out.push({requirement:req,maxRequirement:max||0,bonus,source:clean(src),confidence:'High'})};let m;
    const patterns=[/\$\s*([0-9,]+(?:\.\d+)?)\s*(?:to|–|-|—)\s*\$\s*([0-9,]+(?:\.\d+)?)\s*(?:to earn|=|\s+)\s*(?:the\s*)?\$\s*([0-9,]+(?:\.\d+)?)\s*(?:bonus)?/gi,/\$\s*([0-9,]+(?:\.\d+)?)\s*(?:or more|\+)\s*(?:to earn|=|\s+)\s*(?:the\s*)?\$\s*([0-9,]+(?:\.\d+)?)\s*(?:bonus)?/gi];
    while((m=patterns[0].exec(text)))push(m[1],m[2],m[3],m[0]);while((m=patterns[1].exec(text)))push(m[1],0,m[2],m[0]);
    const seen=new Set();return out.filter(t=>{const k=t.requirement+'|'+t.bonus;if(seen.has(k))return false;seen.add(k);return true}).sort((a,b)=>a.requirement-b.requirement)}
  function promoCode(raw){const patterns=[/(?:promo(?:tional)?|offer|coupon)\s+code\s*(?:is|:|=)?\s*([A-Z0-9][A-Z0-9\-]{3,})/gi,/(?:apply|use|using)\s+(?:promo(?:tional)?\s+code\s+)?([A-Z0-9][A-Z0-9\-]{3,})\s+at\s+the\s+time\s+of\s+account\s+opening/gi];let pick='';let src='';patterns.forEach(re=>{let m;while((m=re.exec(raw))){const c=String(m[1]||'').toUpperCase();if(/\d/.test(c)&&!/PROMOTIONAL|OBTAINED|THROUGH|VALID|OFFER|CODE/i.test(c)){pick=c;src=m[0]}}});return pick?{value:pick,source:src,confidence:'High'}:null}
  function openBy(raw,lines){const candidates=allMatch(lines,[/offer expires/i,/through and including/i,/open.*?by/i,/apply.*?by/i,/valid through/i,/offer ends/i]).filter(x=>!isDisclosure(x));for(const l of candidates){const d=dates(l);if(d.length)return{value:d[d.length-1].iso,display:pretty(d[d.length-1].iso),source:l,confidence:'High'}}return null}
  function requirements(raw,lines,tierList){const l=lineMatch(lines,[/direct deposits?.*within/i,/within.*direct deposits?/i,/Qualifying Direct Deposits/i,/Deposit Period/i,/qualifying electronic deposits/i])||'';const ds=days(l+' '+raw.match(/90-day Deposit Period|ninety\s*\(90\)\s*days|within 90 days/i)?.[0]||'');let reqDays=(ds.find(d=>d.days===90)||ds[0]||{}).days||0;if(/90-day Deposit Period|ninety\s*\(90\)\s*days|within 90 days/i.test(raw))reqDays=90;let count=/two or more|at least two|\b2\b.*direct deposits/i.test(raw)?2:0;const target=tierList[tierList.length-1];let reqMoney=target?.requirement||0;let reqIsTotal=!!target||/total|totaled|totaling|aggregate|cumulative|combined/i.test(l+raw);if(!reqMoney){const ms=monies(l).filter(x=>x.value>=100);reqMoney=ms.sort((a,b)=>b.value-a.value)[0]?.value||0}return{reqDays,count,reqMoney,reqIsTotal,source:l,targetTier:target||null}}
  function funding(raw,lines){const l=lineMatch(lines,[/funded with.*within/i,/minimum deposit required to open/i,/minimum initial deposit/i,/minimum opening deposit/i]);const d=days(l);const ms=monies(l).filter(x=>x.value>0&&x.value<1000);return{fundedDays:/within/i.test(l)?(d[0]?.days||0):0,fundingAmount:ms[0]?.value||0,source:l}}
  function fee(raw,lines){const l=allMatch(lines,[/monthly maintenance fee|monthly service fee|monthly account fee|monthly fee/i]).find(x=>monies(x).some(m=>m.value>0&&m.value<100)&&!isDisclosure(x))||'';const fee=monies(l).filter(x=>x.value>0&&x.value<100).sort((a,b)=>b.value-a.value)[0]?.value||0;const waivers=[];const add=(label,re)=>{if(re.test(raw))waivers.push(label)};add('$5,000 average monthly balance',/average monthly balance.*\$\s*5,?000|\$\s*5,?000.*average monthly balance/i);add('$1,500+ combined monthly direct deposits',/combined monthly direct deposits.*\$\s*1,?500|\$\s*1,?500.*combined monthly direct deposits/i);add('$1,500+ minimum average account balance',/minimum average account balance.*\$\s*1,?500|\$\s*1,?500.*minimum average account balance/i);add('Age/military/rewards waiver may apply',/age 13-24|age 65|military|Smart Rewards|under the age of 25/i);return{fee,waivers:uniq(waivers),source:l}}
  function counts(raw){const out=[];if(/regular monthly income|regular recurring.*income/i.test(raw))out.push('Regular recurring income direct deposit');if(/ACH|Automated Clearing House/i.test(raw))out.push('ACH direct deposit');if(/salary|paycheck|pension|Social Security|government benefits|employer|payroll/i.test(raw))out.push('Salary/paycheck, pension, Social Security/government benefits, employer/government income');if(/account and routing numbers/i.test(raw))out.push('Direct deposit using account and routing numbers');return uniq(out)}
  function notCounts(raw){const out=[];const add=(label,re)=>{if(re.test(raw))out.push(label)};add('Teller deposits',/teller deposits/i);add('Wire transfers',/wire transfers|incoming wires|\bwires\b/i);add('Debit card transfers',/debit card transfers/i);add('ATM transfers or deposits',/ATM transfers or deposits|ATM deposits/i);add('Online/Mobile Banking transfers or deposits',/Online and Mobile Banking transfers or deposits|mobile banking transfers|online transfers/i);add('Bank/brokerage/Merrill transfers',/bank or brokerage account|Merrill investment account|brokerage transfers/i);add('Person-to-person payments / P2P transfers',/person-to-person|person to person|P2P/i);add('Zelle incoming payments',/Zelle/i);add('Mobile/check deposits',/mobile check deposits|mobile deposits|check deposits/i);add('Internal/account-to-account transfers',/internal transfers|account-to-account|one account to another/i);add('Other electronic deposits',/Other electronic deposits/i);return uniq(out)}
  function eligibility(raw){const out=[];if(/new .*checking|new eligible|new consumer/i.test(raw))out.push('New checking customer/account required.');if(/within the last twelve|within the last 12|past 12|last 12/i.test(raw))out.push('Not eligible if you owned/co-owned or received a related checking bonus within the last 12 months.');if(/Fiduciary|trusts|business accounts are not eligible/i.test(raw))out.push('Fiduciary/trust and business accounts may not be eligible.');if(/cannot be combined|may not be combined/i.test(raw))out.push('Cannot be combined with other checking bonus offers.');if(/one bonus per account|one bonus per customer/i.test(raw))out.push('Limited to one bonus per account/customer.');if(/1099|taxable|Internal Revenue Service|IRS|W-9|W-8/i.test(raw))out.push('Bonus may be taxable and reported on Form 1099/IRS.');return uniq(out)}
  function payout(raw,lines){const l=lineMatch(lines,[/within sixty|within 60|120th day|day 120|within thirty|within 30|deposit.*bonus|credited.*bonus/i]);if(/within sixty|within 60/i.test(l))return{value:'within 60 days after the requirement/deposit period ends and requirements are satisfied',source:l};if(/120th day|day 120/i.test(raw))return{value:'after day 90 assessment; deposited on or about day 120 if qualified',source:l};if(/within thirty|within 30|up to 30/i.test(l))return{value:'within 30 days after requirements are met/assessed',source:l};return{value:'payout timing needs review',source:l}}
  function singleBonus(lines){const c=[];lines.filter(l=>/bonus|earn|receive|cash/i.test(l)&&!isDisclosure(l)).forEach(l=>monies(l).forEach(m=>{let score=0;if(/bonus/i.test(l))score+=4;if(/earn|receive|credited|cash/i.test(l))score+=2;if(/deposit|balance|fee|waive|minimum|APY/i.test(l))score-=2;if(m.value>0&&m.value<3000)c.push({...m,score,source:l})}));return c.sort((a,b)=>b.score-a.score||b.value-a.value)[0]||null}
  function analyze(input,opts={}){const source=window.tcV3ResolveSource?window.tcV3ResolveSource(input,opts):{raw:input||'',kind:'direct'};const original=source.raw||'';const raw=normalize(original);const lines=split(raw);let tierList=tiers(raw);const b=bank(raw);const p=promoCode(raw);const exp=openBy(raw,lines);const req=requirements(raw,lines,tierList);const fund=funding(raw,lines);const feeObj=fee(raw,lines);const pay=payout(raw,lines);let bonus=tierList.length?(opts.tierIndex!=null?tierList[opts.tierIndex]?.bonus:tierList[tierList.length-1].bonus):singleBonus(lines)?.value||0;const targetTier=tierList.length?(opts.tierIndex!=null?tierList[opts.tierIndex]:tierList[tierList.length-1]):null;
    const result={version:VER,source,sourceKind:source.kind,sourceId:source.sourceId,sourceLength:source.length,bank:b,acct:account(raw),raw:original,normalizedRaw:raw,tiered:!!tierList.length,tiers:tierList,targetTier,bonus,selectedBonus:bonus,bonusTierText:tierList.map(t=>`${money(t.bonus)} for ${money(t.requirement)}+ DD`).join(' / '),code:p?.value||'',promoCode:p,openBy:exp?.value||'',expiration:exp,reqDays:req.reqDays,reqMoney:req.reqMoney,reqIsTotal:req.reqIsTotal,count:req.count,reqSource:req.source,fundedDays:fund.fundedDays,fundingAmount:fund.fundingAmount,fundingSource:fund.source,fee:feeObj.fee,monthlyFee:feeObj.fee?{value:money(feeObj.fee)+' monthly fee',amount:feeObj.fee,source:feeObj.source}:null,waivers:feeObj.waivers,counts:counts(raw),not:notCounts(raw),notCounts:notCounts(raw),eligibilityText:eligibility(raw).join('\n'),payout:pay.value,payoutText:pay.value,payoutSource:pay.source,early:'Keep account open and in good standing until bonus payout; closing/restriction before payout can forfeit bonus.',reviewFlags:[],clear:false,bankProfilesVersion:'v3-core'};
    if(!result.bonus)result.reviewFlags.push('Bonus amount needs review.');if(!result.reqDays&&/direct deposit|qualifying deposit/i.test(raw))result.reviewFlags.push('Requirement deadline needs review.');if(/promo code|promotional code|offer code/i.test(raw)&&!result.code)result.reviewFlags.push('Promo code mentioned but exact code needs review.');if(/offer expires|through and including|open.*by/i.test(raw)&&!result.openBy)result.reviewFlags.push('Promo expiration/open-by date needs review.');result.clear=!!(result.bonus&&result.reqDays);
    result.suggestedTimers=[];if(result.openBy)result.suggestedTimers.push({kind:'due',text:'Promo expiration / open-by deadline',date:result.openBy});if(result.reqDays)result.suggestedTimers.push({kind:'days',text:'Bonus requirement deadline',daysRequired:result.reqDays});if(result.fundedDays)result.suggestedTimers.push({kind:'days',text:'Funding deadline',daysRequired:result.fundedDays});
    result.actionPlan=[`1. Open one eligible account${result.openBy?' by '+pretty(result.openBy):''}${result.code?' using promo code '+result.code:''}.`,result.fundedDays?`2. Fund the account${result.fundingAmount?' with at least '+money(result.fundingAmount):''} within ${result.fundedDays} days.`:'',`3. Complete ${result.count?'at least '+result.count+' ':''}qualifying Direct Deposits${result.reqMoney?`${result.reqIsTotal?' totaling ':' of '}${money(result.reqMoney)}+${result.reqIsTotal?'':' each'}`:''}${result.reqDays?' within '+result.reqDays+' days':''}.`,`4. Bonus payout: ${result.payout}.`,'5. Keep account open and in good standing until payout.'].filter(Boolean).join('\n');
    window.__tcV3AnalysisResult=result;window.__tcCurrentAnalysisResult=result;return result;}
  window.tcV3Analyze=analyze;window.tcUnifiedAnalyze=analyze;window.tcStrictAnalyze=analyze;window.tcV3EngineVersion=VER;
})();
